package com.trimble.ag.filemonitor.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FILE_INFO.
 */
public class FileInfo {

    private Long id;
    private String filePath;
    private String appname;
    private String descFilePath;
    private java.util.Date registeredTime;
    private java.util.Date lastZipTime;
    private Long lastFileSize;
    private String awsFileId;
    private Long flag;
    private Long status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FileInfo() {
    }

    public FileInfo(Long id) {
        this.id = id;
    }

    public FileInfo(Long id, String filePath, String appname, String descFilePath, java.util.Date registeredTime, java.util.Date lastZipTime, Long lastFileSize, String awsFileId, Long flag, Long status) {
        this.id = id;
        this.filePath = filePath;
        this.appname = appname;
        this.descFilePath = descFilePath;
        this.registeredTime = registeredTime;
        this.lastZipTime = lastZipTime;
        this.lastFileSize = lastFileSize;
        this.awsFileId = awsFileId;
        this.flag = flag;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getAppname() {
        return appname;
    }

    public void setAppname(String appname) {
        this.appname = appname;
    }

    public String getDescFilePath() {
        return descFilePath;
    }

    public void setDescFilePath(String descFilePath) {
        this.descFilePath = descFilePath;
    }

    public java.util.Date getRegisteredTime() {
        return registeredTime;
    }

    public void setRegisteredTime(java.util.Date registeredTime) {
        this.registeredTime = registeredTime;
    }

    public java.util.Date getLastZipTime() {
        return lastZipTime;
    }

    public void setLastZipTime(java.util.Date lastZipTime) {
        this.lastZipTime = lastZipTime;
    }

    public Long getLastFileSize() {
        return lastFileSize;
    }

    public void setLastFileSize(Long lastFileSize) {
        this.lastFileSize = lastFileSize;
    }

    public String getAwsFileId() {
        return awsFileId;
    }

    public void setAwsFileId(String awsFileId) {
        this.awsFileId = awsFileId;
    }

    public Long getFlag() {
        return flag;
    }

    public void setFlag(Long flag) {
        this.flag = flag;
    }

    public Long getStatus() {
        return status;
    }

    public void setStatus(Long status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
