package com.trimble.ag.ats.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LOCATION".
 */
public class Location {

    private Long locationId;
    private Double latitude;
    private Double longtitude;
    private Double speed;
    private Double heading;
    private Long time;
    private Boolean isSynced;
    private String orgId;
    private Double altitude;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Location() {
    }

    public Location(Long locationId) {
        this.locationId = locationId;
    }

    public Location(Long locationId, Double latitude, Double longtitude, Double speed, Double heading, Long time, Boolean isSynced, String orgId, Double altitude) {
        this.locationId = locationId;
        this.latitude = latitude;
        this.longtitude = longtitude;
        this.speed = speed;
        this.heading = heading;
        this.time = time;
        this.isSynced = isSynced;
        this.orgId = orgId;
        this.altitude = altitude;
    }

    public Long getLocationId() {
        return locationId;
    }

    public void setLocationId(Long locationId) {
        this.locationId = locationId;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongtitude() {
        return longtitude;
    }

    public void setLongtitude(Double longtitude) {
        this.longtitude = longtitude;
    }

    public Double getSpeed() {
        return speed;
    }

    public void setSpeed(Double speed) {
        this.speed = speed;
    }

    public Double getHeading() {
        return heading;
    }

    public void setHeading(Double heading) {
        this.heading = heading;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Boolean getIsSynced() {
        return isSynced;
    }

    public void setIsSynced(Boolean isSynced) {
        this.isSynced = isSynced;
    }

    public String getOrgId() {
        return orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    public Double getAltitude() {
        return altitude;
    }

    public void setAltitude(Double altitude) {
        this.altitude = altitude;
    }

    // KEEP METHODS - put your custom methods here
    public Location(final android.location.Location location){
       setLocationId(location.getTime());
       setTime(location.getTime());
       setLatitude(location.getLatitude());
       setLongtitude(location.getLongitude());
       setHeading((double)location.getBearing());
       setSpeed((double)location.getSpeed());
       setIsSynced(false);
    }
    // KEEP METHODS END

}
