package com.trimble.ag.ats.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SETTINGS".
 */
public class Settings {

    private String settingsKey;
    private String settingsValue;
    private Long Type;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Settings() {
    }

    public Settings(String settingsKey) {
        this.settingsKey = settingsKey;
    }

    public Settings(String settingsKey, String settingsValue, Long Type) {
        this.settingsKey = settingsKey;
        this.settingsValue = settingsValue;
        this.Type = Type;
    }

    public String getSettingsKey() {
        return settingsKey;
    }

    public void setSettingsKey(String settingsKey) {
        this.settingsKey = settingsKey;
    }

    public String getSettingsValue() {
        return settingsValue;
    }

    public void setSettingsValue(String settingsValue) {
        this.settingsValue = settingsValue;
    }

    public Long getType() {
        return Type;
    }

    public void setType(Long Type) {
        this.Type = Type;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
