package com.trimble.agmantra.filecodec.res;

public enum PredefinedResources {	
		  UIDTYPE_UNKNOWN,
		  UIDTYPE_UNIT,
		  UIDTYPE_ACTION,
		  UIDTYPE_PEST,
		  UIDTYPE_CHARGE_UNIT,
		  UIDTYPE_ICONGROUP,
		  UIDTYPE_NOTE_TYPE,
		  UIDTYPE_GROWTH_STAGE,
		  UIDTYPE_SOIL_CONDITION,
		  UIDTYPE_SOIL_TYPE,
		  UIDTYPE_APP_METHOD,
		  UIDTYPE_SKY_CONDITION,
		  UIDTYPE_WIND_DIR,
		  UIDTYPE_CARRIER,
		  UIDTYPE_SUPPLY_TYPE,
		  UIDTYPE_PEOPLE,
		  UIDTYPE_EQUIPMENT,
		  UIDTYPE_SUPPLY,
		  UIDTYPE_FIELD,
		  UIDTYPE_COMMODITY,
		  UIDTYPE_CROP,
		  UIDTYPE_PROJECT		  
};
