package com.trimble.ag.ats.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.trimble.ag.ats.entity.Organization;
import com.trimble.ag.ats.entity.User;

import com.trimble.ag.ats.entity.User_Organization;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER__ORGANIZATION".
*/
public class User_OrganizationDao extends AbstractDao<User_Organization, Long> {

    public static final String TABLENAME = "USER__ORGANIZATION";

    /**
     * Properties of entity User_Organization.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ServerMode = new Property(1, Integer.class, "serverMode", false, "SERVER_MODE");
        public final static Property OrgId = new Property(2, String.class, "orgId", false, "ORG_ID");
        public final static Property UserId = new Property(3, long.class, "userId", false, "USER_ID");
    };

    private DaoSession daoSession;

    private Query<User_Organization> user_User_OrganizationListQuery;
    private Query<User_Organization> organization_User_OrganizationListQuery;

    public User_OrganizationDao(DaoConfig config) {
        super(config);
    }
    
    public User_OrganizationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER__ORGANIZATION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SERVER_MODE\" INTEGER," + // 1: serverMode
                "\"ORG_ID\" TEXT NOT NULL ," + // 2: orgId
                "\"USER_ID\" INTEGER NOT NULL );"); // 3: userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER__ORGANIZATION\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, User_Organization entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer serverMode = entity.getServerMode();
        if (serverMode != null) {
            stmt.bindLong(2, serverMode);
        }
        stmt.bindString(3, entity.getOrgId());
        stmt.bindLong(4, entity.getUserId());
    }

    @Override
    protected void attachEntity(User_Organization entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public User_Organization readEntity(Cursor cursor, int offset) {
        User_Organization entity = new User_Organization( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // serverMode
            cursor.getString(offset + 2), // orgId
            cursor.getLong(offset + 3) // userId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, User_Organization entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setServerMode(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setOrgId(cursor.getString(offset + 2));
        entity.setUserId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(User_Organization entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(User_Organization entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "user_OrganizationList" to-many relationship of User. */
    public List<User_Organization> _queryUser_User_OrganizationList(long userId) {
        synchronized (this) {
            if (user_User_OrganizationListQuery == null) {
                QueryBuilder<User_Organization> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UserId.eq(null));
                user_User_OrganizationListQuery = queryBuilder.build();
            }
        }
        Query<User_Organization> query = user_User_OrganizationListQuery.forCurrentThread();
        query.setParameter(0, userId);
        return query.list();
    }

    /** Internal query to resolve the "user_OrganizationList" to-many relationship of Organization. */
    public List<User_Organization> _queryOrganization_User_OrganizationList(String orgId) {
        synchronized (this) {
            if (organization_User_OrganizationListQuery == null) {
                QueryBuilder<User_Organization> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.OrgId.eq(null));
                organization_User_OrganizationListQuery = queryBuilder.build();
            }
        }
        Query<User_Organization> query = organization_User_OrganizationListQuery.forCurrentThread();
        query.setParameter(0, orgId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getOrganizationDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM USER__ORGANIZATION T");
            builder.append(" LEFT JOIN ORGANIZATION T0 ON T.\"ORG_ID\"=T0.\"ORG_ID\"");
            builder.append(" LEFT JOIN USER T1 ON T.\"USER_ID\"=T1.\"USER_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected User_Organization loadCurrentDeep(Cursor cursor, boolean lock) {
        User_Organization entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Organization organization = loadCurrentOther(daoSession.getOrganizationDao(), cursor, offset);
         if(organization != null) {
            entity.setOrganization(organization);
        }
        offset += daoSession.getOrganizationDao().getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
         if(user != null) {
            entity.setUser(user);
        }

        return entity;    
    }

    public User_Organization loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<User_Organization> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<User_Organization> list = new ArrayList<User_Organization>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<User_Organization> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<User_Organization> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
