package com.trimble.scout.encode;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table FEATURE.
 */
public class Feature {

    private Long id;
    private Long area;
    private Long color;
    private Integer thickness;
    private Long perimeter;
    private byte[] vertex;
    private Integer bottomRightX;
    private Integer bottomRightY;
    private Integer topLeftX;
    private Integer topLeftY;
    private Long featureTypeId;
    private Long fieldId;

  


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Feature() {
    }

    public Feature(Long id) {
        this.id = id;
    }

    public Feature(Long id, Long area, Long color, Integer thickness, Long perimeter, byte[] vertex, Integer bottomRightX, Integer bottomRightY, Integer topLeftX, Integer topLeftY, Long featureTypeId, Long fieldId) {
        this.id = id;
        this.area = area;
        this.color = color;
        this.thickness = thickness;
        this.perimeter = perimeter;
        this.vertex = vertex;
        this.bottomRightX = bottomRightX;
        this.bottomRightY = bottomRightY;
        this.topLeftX = topLeftX;
        this.topLeftY = topLeftY;
        this.featureTypeId = featureTypeId;
        this.fieldId = fieldId;
    }

    

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getArea() {
        return area;
    }

    public void setArea(Long area) {
        this.area = area;
    }

    public Long getColor() {
        return color;
    }

    public void setColor(Long color) {
        this.color = color;
    }

    public Integer getThickness() {
        return thickness;
    }

    public void setThickness(Integer thickness) {
        this.thickness = thickness;
    }

    public Long getPerimeter() {
        return perimeter;
    }

    public void setPerimeter(Long perimeter) {
        this.perimeter = perimeter;
    }

    public byte[] getVertex() {
        return vertex;
    }

    public void setVertex(byte[] vertex) {
        this.vertex = vertex;
    }

    public Integer getBottomRightX() {
        return bottomRightX;
    }

    public void setBottomRightX(Integer bottomRightX) {
        this.bottomRightX = bottomRightX;
    }

    public Integer getBottomRightY() {
        return bottomRightY;
    }

    public void setBottomRightY(Integer bottomRightY) {
        this.bottomRightY = bottomRightY;
    }

    public Integer getTopLeftX() {
        return topLeftX;
    }

    public void setTopLeftX(Integer topLeftX) {
        this.topLeftX = topLeftX;
    }

    public Integer getTopLeftY() {
        return topLeftY;
    }

    public void setTopLeftY(Integer topLeftY) {
        this.topLeftY = topLeftY;
    }

    public Long getFeatureTypeId() {
        return featureTypeId;
    }

    public void setFeatureTypeId(Long featureTypeId) {
        this.featureTypeId = featureTypeId;
    }

    public Long getFieldId() {
        return fieldId;
    }

    public void setFieldId(Long fieldId) {
        this.fieldId = fieldId;
    }

  

}
