/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_trimble_agmantra_utils_ZipUtils */

#ifndef _Included_com_trimble_agmantra_utils_ZipUtils
#define _Included_com_trimble_agmantra_utils_ZipUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_trimble_agmantra_utils_ZipUtils
 * Method:    createJobZipFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_trimble_agmantra_utils_ZipUtils_createJobZipFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
