package com.trimble.agmantra.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CLIENT.
 */
public class Client {

    private Long id;
    private String desc;
    private Boolean isServerdata;
    private Integer locked;
    private Integer deleted;
    private Integer status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Client() {
    }

    public Client(Long id) {
        this.id = id;
    }

    public Client(Long id, String desc, Boolean isServerdata, Integer locked, Integer deleted, Integer status) {
        this.id = id;
        this.desc = desc;
        this.isServerdata = isServerdata;
        this.locked = locked;
        this.deleted = deleted;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Boolean getIsServerdata() {
        return isServerdata;
    }

    public void setIsServerdata(Boolean isServerdata) {
        this.isServerdata = isServerdata;
    }

    public Integer getLocked() {
        return locked;
    }

    public void setLocked(Integer locked) {
        this.locked = locked;
    }

    public Integer getDeleted() {
        return deleted;
    }

    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
