package com.trimble.agmantra.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table COMMODITY.
 */
public class Commodity {

    private Long id;
    private String name;
    private Long unitConv;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Commodity() {
    }

    public Commodity(Long id) {
        this.id = id;
    }

    public Commodity(Long id, String name, Long unitConv) {
        this.id = id;
        this.name = name;
        this.unitConv = unitConv;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getUnitConv() {
        return unitConv;
    }

    public void setUnitConv(Long unitConv) {
        this.unitConv = unitConv;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
