package com.trimble.agmantra.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table EQUIPMENTS.
 */
public class Equipments {

    private Long id;
    private String name;
    private Integer status;
    private Integer width;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Equipments() {
    }

    public Equipments(Long id) {
        this.id = id;
    }

    public Equipments(Long id, String name, Integer status, Integer width) {
        this.id = id;
        this.name = name;
        this.status = status;
        this.width = width;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getWidth() {
        return width;
    }

    public void setWidth(Integer width) {
        this.width = width;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
