package com.trimble.agmantra.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LANGUAGE.
 */
public class Language {

    private Long languageid;
    private String language;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Language() {
    }

    public Language(Long languageid) {
        this.languageid = languageid;
    }

    public Language(Long languageid, String language) {
        this.languageid = languageid;
        this.language = language;
    }

    public Long getLanguageid() {
        return languageid;
    }

    public void setLanguageid(Long languageid) {
        this.languageid = languageid;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
