package com.trimble.agmantra.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table MAPPING.
 */
public class Mapping {

    private Long id;
    private Integer AttributeId;
    private Integer AttrItemID;
    private Integer GroupID;
    private Integer Level;
    private Integer MappingID;
    private Integer NextmappingID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Mapping() {
    }

    public Mapping(Long id) {
        this.id = id;
    }

    public Mapping(Long id, Integer AttributeId, Integer AttrItemID, Integer GroupID, Integer Level, Integer MappingID, Integer NextmappingID) {
        this.id = id;
        this.AttributeId = AttributeId;
        this.AttrItemID = AttrItemID;
        this.GroupID = GroupID;
        this.Level = Level;
        this.MappingID = MappingID;
        this.NextmappingID = NextmappingID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAttributeId() {
        return AttributeId;
    }

    public void setAttributeId(Integer AttributeId) {
        this.AttributeId = AttributeId;
    }

    public Integer getAttrItemID() {
        return AttrItemID;
    }

    public void setAttrItemID(Integer AttrItemID) {
        this.AttrItemID = AttrItemID;
    }

    public Integer getGroupID() {
        return GroupID;
    }

    public void setGroupID(Integer GroupID) {
        this.GroupID = GroupID;
    }

    public Integer getLevel() {
        return Level;
    }

    public void setLevel(Integer Level) {
        this.Level = Level;
    }

    public Integer getMappingID() {
        return MappingID;
    }

    public void setMappingID(Integer MappingID) {
        this.MappingID = MappingID;
    }

    public Integer getNextmappingID() {
        return NextmappingID;
    }

    public void setNextmappingID(Integer NextmappingID) {
        this.NextmappingID = NextmappingID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
