/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <string.h>
#include <sys/stat.h>
#include <stdlib.h>
#include <stdio.h>
#include <malloc.h>



/* Header for class com_trimble_zipreader_NativeZipReader */

#ifndef _Included_com_trimble_zipreader_NativeZipReader
#define _Included_com_trimble_zipreader_NativeZipReader
#ifdef __cplusplus
extern "C" {
#endif

#define LOG_DATA_NDK
#define BUFSIZ 8192
#define  LOG_TAG    "TRIMBLE"
#define DEBUG_TAG	"TRIMBLE_DEBUG"

#ifdef LOG_DATA_NDK
#define  LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)
#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)
#endif


/*
 * Class:     com_trimble_zipreader_NativeZipReader
 * Method:    loadFileFromZipFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_trimble_zipreader_NativeZipReader_loadFileFromZipFile
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
