package com.trimble.agmantra.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.SqlUtils;

import com.trimble.agmantra.entity.Feature;
import com.trimble.agmantra.entity.Job;
import com.trimble.agmantra.entity.TemplateType;

import com.trimble.agmantra.entity.JobTransaction;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table JOB_TRANSACTION.
*/
public class JobTransactionDao extends AbstractDao<JobTransaction, Long> {

    public static final String TABLENAME = "JOB_TRANSACTION";

    /**
     * Properties of entity JobTransaction.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Status = new Property(1, Integer.class, "status", false, "STATUS");
        public final static Property Passid = new Property(2, Integer.class, "passid", false, "PASSID");
        public final static Property AttrindexId = new Property(3, Integer.class, "attrindexId", false, "ATTRINDEX_ID");
        public final static Property FeatureId = new Property(4, Long.class, "featureId", false, "FEATURE_ID");
        public final static Property JobId = new Property(5, Long.class, "jobId", false, "JOB_ID");
        public final static Property TemplateTypeId = new Property(6, Long.class, "templateTypeId", false, "TEMPLATE_TYPE_ID");
    };

    private DaoSession daoSession;


    public JobTransactionDao(DaoConfig config) {
        super(config);
    }
    
    public JobTransactionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'JOB_TRANSACTION' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'STATUS' INTEGER," + // 1: status
                "'PASSID' INTEGER," + // 2: passid
                "'ATTRINDEX_ID' INTEGER," + // 3: attrindexId
                "'FEATURE_ID' INTEGER," + // 4: featureId
                "'JOB_ID' INTEGER," + // 5: jobId
                "'TEMPLATE_TYPE_ID' INTEGER);"); // 6: templateTypeId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'JOB_TRANSACTION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, JobTransaction entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(2, status);
        }
 
        Integer passid = entity.getPassid();
        if (passid != null) {
            stmt.bindLong(3, passid);
        }
 
        Integer attrindexId = entity.getAttrindexId();
        if (attrindexId != null) {
            stmt.bindLong(4, attrindexId);
        }
 
        Long featureId = entity.getFeatureId();
        if (featureId != null) {
            stmt.bindLong(5, featureId);
        }
 
        Long jobId = entity.getJobId();
        if (jobId != null) {
            stmt.bindLong(6, jobId);
        }
 
        Long templateTypeId = entity.getTemplateTypeId();
        if (templateTypeId != null) {
            stmt.bindLong(7, templateTypeId);
        }
    }

    @Override
    protected void attachEntity(JobTransaction entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public JobTransaction readEntity(Cursor cursor, int offset) {
        JobTransaction entity = new JobTransaction( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // status
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // passid
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // attrindexId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // featureId
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // jobId
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // templateTypeId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, JobTransaction entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStatus(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setPassid(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setAttrindexId(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setFeatureId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setJobId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setTemplateTypeId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(JobTransaction entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(JobTransaction entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTemplateTypeDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getFeatureDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getJobDao().getAllColumns());
            builder.append(" FROM JOB_TRANSACTION T");
            builder.append(" LEFT JOIN TEMPLATE_TYPE T0 ON T.'TEMPLATE_TYPE_ID'=T0.'_id'");
            builder.append(" LEFT JOIN FEATURE T1 ON T.'FEATURE_ID'=T1.'_id'");
            builder.append(" LEFT JOIN JOB T2 ON T.'JOB_ID'=T2.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected JobTransaction loadCurrentDeep(Cursor cursor, boolean lock) {
        JobTransaction entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        TemplateType templateType = loadCurrentOther(daoSession.getTemplateTypeDao(), cursor, offset);
        entity.setTemplateType(templateType);
        offset += daoSession.getTemplateTypeDao().getAllColumns().length;

        Feature feature = loadCurrentOther(daoSession.getFeatureDao(), cursor, offset);
        entity.setFeature(feature);
        offset += daoSession.getFeatureDao().getAllColumns().length;

        Job job = loadCurrentOther(daoSession.getJobDao(), cursor, offset);
        entity.setJob(job);

        return entity;    
    }

    public JobTransaction loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<JobTransaction> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<JobTransaction> list = new ArrayList<JobTransaction>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<JobTransaction> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<JobTransaction> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
